FROM python:3.11-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
# Worker olduğu için EXPOSE portuna gerek yok
CMD ["python", "weather_service.py"]